### ISSUE TITLE
need:   context: undefined   ,not supported yet ?

### ISSUE THREAD

**Issue by zuohuadong** [codejie/fastify-apollo-step#2]
need:   context: undefined   ,not supported yet ?

**Comment by zuohuadong** [comment]
![image](https://user-images.githubusercontent.com/11203929/47063384-62df2880-d20d-11e8-8d2e-6c432e563cf9.png)

https://github.com/fastify/fastify/blob/master/docs/Hooks.md

**Comment by codejie** [comment]
maybe you could use this context as usually, I am just not sure how to use it. so I marked 'not supported'.
